#include <stddev.h>
#include <Drivers/PortIO/ports.c>
#include <Drivers/Text/text.c>
#include <Drivers/Sound/sound.c>
#include <Drivers/VGA/vga.c>
#include <Drivers/Disk/disk.c>
#include <Drivers/Keyboard/keyboard.c>
#include <Etcetera/etc.h>
#include <Programs/write.c>
